import { InstanceofGeneratorDefinition } from "./zocker.js";
import {z} from "zod";

import {
	NumberGenerator,
	BigintGenerator,
	BooleanGenerator,
	DateGenerator,
	SymbolGenerator,
	OptionalGenerator,
	NullableGenerator,
	AnyGenerator,
	UnknownGenerator,
	ArrayGenerator,
	TupleGenerator,
	RecordGenerator,
	MapGenerator,
	SetGenerator,
	ObjectGenerator,
	UnionGenerator,
	EnumGenerator,
	DefaultGenerator,
	PromiseGenerator,
	LazyGenerator,
	IntersectionGenerator,
	ReadonlyGenerator,
	StringGenerator,
	CUIDGenerator,
	CUID2Generator,
	IPv4Generator,
	IPv6Generator,
	UUIDGenerator,
	E164Generator,
	EmailGenerator,
	ISODateGenerator,
	ISODateTimeGenerator,
	ISOTimeGenerator,
	ISODurationGenerator,
	NanoIDGenerator,
	ULIDGenerator,
	CIDRv4Generator,
	CIDRv6Generator,
	URLGenerator,
	PipeGenerator,
	EmojiGenerator,
	Base64Generator,
	Base64URLGenerator,
	GUIDGenerator,
	KSUIDGenerator,
	XIDGenerator
} from "./generators/index.js";

export const default_generators: InstanceofGeneratorDefinition<any>[] = [
	XIDGenerator,
	KSUIDGenerator,
	Base64Generator,
	Base64URLGenerator,
	EmojiGenerator,
	URLGenerator,
	CIDRv4Generator,
	CIDRv6Generator,
	ULIDGenerator,
	NanoIDGenerator,
	ISODateGenerator,
	ISODateTimeGenerator,
	ISOTimeGenerator,
	ISODurationGenerator,
	EmailGenerator,
	E164Generator,
	GUIDGenerator,
	UUIDGenerator,
	IPv4Generator,
	IPv6Generator,
	CUID2Generator,
	CUIDGenerator,
	StringGenerator,
	NumberGenerator,
	BigintGenerator,
	BooleanGenerator,
	DateGenerator,
	SymbolGenerator,
	OptionalGenerator,
	NullableGenerator,
	AnyGenerator,
	UnknownGenerator,
	PipeGenerator,
	ArrayGenerator,
	TupleGenerator,
	RecordGenerator,
	MapGenerator,
	SetGenerator,
	ObjectGenerator,
	UnionGenerator,
	EnumGenerator,
	DefaultGenerator,
	PromiseGenerator,
	LazyGenerator,
	ReadonlyGenerator,
	{
		schema: z.core.$ZodVoid,
		generator: () => {},
		match: "instanceof"
	},
	{
		schema: z.core.$ZodUndefined,
		generator: () => undefined,
		match: "instanceof"
	},
	{
		schema: z.core.$ZodNull,	
		generator: () => null,
		match: "instanceof"
	},
	{
		schema: z.core.$ZodNaN,
		generator: () => NaN,
		match: "instanceof"
	},
	{
		schema: z.core.$ZodLiteral,
		generator: (schema: z.core.$ZodLiteral) => schema._zod.def.values[0],
		match: "instanceof"
	},
	{
		schema: z.core.$ZodNever,
		generator: () => void 0,
		match: "instanceof"
	},
	IntersectionGenerator
];
